import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Post from "./Post";
import { useState, useEffect } from "react";
import Modal from "react-modal";
import MakePostButton from "./MakePostButton";

export default function Home({ posts_prop, filteruser }) {
    const [posts, setPosts] = useState(posts_prop);
    const [modalIsOpen, setModalIsOpen] = useState(false);
    const [username, setUsername] = useState("");

    function fetchPosts() {
        fetch(`http://localhost:5000/posts?byuser=${"sean"}`)
            .then((res) => res.json())
            .then((data) => setPosts(data));
    }
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div className="fixed top-0 z-10 bg-slate-400 w-full h-12 text-center grid justify-items-end">
                    <p className="items-center p-3">
                        {username.length == 0 ? "login" : "logged in as sean"}
                    </p>
                </div>
                {posts.map((p) => (
                    <Post
                        key={p.id}
                        {...p}
                        fetchPosts={fetchPosts}
                        setModalIsOpen={setModalIsOpen}
                    ></Post>
                ))}
                <Modal
                    isOpen={modalIsOpen}
                    onAfterOpen={() => {}}
                    ariaHideApp={false}
                    contentLabel="Example Modal"
                    style={{
                        overlay: {
                            position: "fixed",
                            top: 0,
                            left: 0,
                            right: 0,
                            bottom: 0,
                            backgroundColor: "rgba(255, 255, 255, 0.75)",
                        },
                        content: {
                            position: "absolute",
                            top: "25%",
                            left: "25%",
                            border: "1px solid #ccc",
                            background: "#fff",
                            overflow: "auto",
                            WebkitOverflowScrolling: "touch",
                            borderRadius: "4px",
                            outline: "none",
                            padding: "20px",
                            width: "50%",
                            height: "50%",
                        },
                    }}
                >
                    <div className="z-20 h-full flex items-center content-center justify-center">
                        <div>
                            <div class="mx-auto flex items-center justify-center h-12 w-12 rounded-full bg-green-100">
                                <svg
                                    class="h-6 w-6 text-green-600"
                                    fill="none"
                                    stroke="currentColor"
                                    viewBox="0 0 24 24"
                                    xmlns="http://www.w3.org/2000/svg"
                                >
                                    <path
                                        stroke-linecap="round"
                                        stroke-linejoin="round"
                                        stroke-width="2"
                                        d="M5 13l4 4L19 7"
                                    ></path>
                                </svg>
                            </div>
                            <p>Successly bought access</p>
                        </div>
                    </div>
                </Modal>
            </main>
            <div className="fixed bottom-10 right-10">
                <MakePostButton fetchPosts={fetchPosts}></MakePostButton>
            </div>
        </div>
    );
}

export async function getStaticProps(context) {
    //const res = await fetch(`http://localhost:5000/posts?byuser=${"sean"}`);
    const res = await fetch(`http://localhost:5000/posts`);
    const posts = await res.json();
    console.log(posts);

    return {
        props: { posts_prop: posts }, // will be passed to the page component as props
    };
}
